// Generated by Wrangler by running `wrangler types`

interface Env {
	SESSION: KVNamespace;
	RESULT_CACHE: KVNamespace;
	OAUTH_CLIENT_ID: "f413f5ac653046e7b41f7b8bd2920c5f";
	OAUTH_CLIENT_SECRET: string;
	OAUTH_REDIRECT_URI: string;
	SESSION_SIGNING_SECRET: string;
	SFPL_CATALOG_INDEX: VectorizeIndex;
	AI: Ai;
}
